import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {getServerSession} from "next-auth";
import Logout from "@/app/logout";
import Link from "next/link";
import React from "react";
import HeadersDiv from "@/app/components/headers-div";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeadersDiv />

        {children}
      </body>
    </html>
  );
}
